# H2를 이용한 local 개발 단계에서 사용
spring:
  datasource:
    driver-class-name: org.h2.Driver
<<<<<<< HEAD
    url: jdbc:h2:tcp://localhost/~/test
=======
    url: jdbc:h2:tcp://localhost/~/test;
>>>>>>> 6e83b9710b003a5e84dd27e7b8dc94a7466abc75
    username: sa
    password:


# MySQL을 이용한 배포 단계에서 사용
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://bancow5-database.c0tjxdlcevpx.ap-northeast-2.rds.amazonaws.com/bancow5
#    username: admin
#    password: bancow5!


  jpa:
    hibernate:
      # H2를 이용한 local 개발 단계에서 사용
      ddl-auto: create
#      # MySQL을 이용한 배포 단계에서 사용
#      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace